import { Request, Response, NextFunction } from "express";
import { ApiResponse } from "../types/common";
import { Category } from "../models/category";
import { createErrorJson } from "../utils/responseWrapper";

// This middleware generates a file name for uploading the category image.
// Later, this file name is used in the Cloudinary configuration to ensure
// that every category image has a consistent and meaningful name
// instead of a random one generated by the service.
const addCategoryNameToReqBody = [
  async (
    req: Request<{ categoryId: string }, {}, any>,
    res: Response<ApiResponse<null>>,
    next: NextFunction
  ) => {
    try {
      const category = await Category.findOne({
        _id: req.params.categoryId,
        isMainCategory: true,
      });

      if (!category) {
        res
          .status(400)
          .json(
            createErrorJson([
              { type: "addCategoryImg", msg: "category_not_found" },
            ])
          );
        return;
      }

      //next middleware or service (e.g. Cloudinary upload configuration)
      // can access name easily.
      req.customData = {
        cateogory_name: category.name,
      };

      next();
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .json(
          createErrorJson([{ type: "general", msg: "BE_something_went_wrong" }])
        );
      return;
    }
  },
];

export default addCategoryNameToReqBody;
